### ISSUE TITLE
"Failed to get a response from item server!"

### ISSUE THREAD

**Issue by Arkpit** [qhris/DiabloSpeech#1]
Having D2 open, the interface open as well with working integration and using the bot command !item only gives the response: "Failed to get a response from item server!"

Cannot find if there is a required place for files to be or anything that points towards this issue.

**Comment by qhris** [comment]
Hey, there's been some changes in DiabloInterface recently which I haven't had time to address yet in this repository.

If you like I'd recommend this [twitch extension](https://www.twitch.tv/ext/l0m154prxsmwu1m0tyic1ei0915byb-0.0.4) which allows viewing the items on stream, which also uses DiabloInterface. This works by using [D2ID](https://github.com/palmettos/D2ID) which takes data from DI and pumps it to the extension via an online service.

Honestly I probably won't be doing much work on this now that D2ID and the twitch extension exists, unless there's still people who want this.

**Comment by Arkpit** [comment]
Thanks for crazy quick response!

Meanwhile I figured out I could use 0.3.1 which worked with d2speech as well and noticed you were using that version for d2id as well ^^

Already tried your extension on twitch and it works great, thanks a bunch and great work! :D
